//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Area_Produccion_Materias_Primas
    {
        [Key]
        public int Area_Produccion_Materia_PrimaID { get; set; }
        public int? Area_ProduccionID { get; set; }
        public int? Materia_PrimaID { get; set; }
        public int? CantidadSaliente { get; set; }
        public System.DateTime? FechaDeSalida { get; set; }
    
        public virtual Area_Produccion Area_Produccion { get; set; }
        public virtual Materias_Primas Materias_Primas { get; set; }
    }
}
