//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Area_Produccion_Control_Piezas
    {
        [Key]
        public int Area_Produccion_Control_PiezasID { get; set; }

        [ForeignKey("Departamentos")]
        public int? DepartamentoID { get; set; }
        public int? Control_Ubicacion_PiezaID { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
    }
}
