//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTM.Models
{
    using RTM.Models.TableDB;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Area_Produccion_Materias_Primas
    {
        [Key]
        public int Area_Produccion_Materia_PrimaID { get; set; }

        [ForeignKey("SubDepartamentos")]
        public int? SubDepartamentoID { get; set; }

        [ForeignKey("Materias_Primas")]
        public int? Materia_PrimaID { get; set; }
        public int? CantidadSaliente { get; set; }
        public System.DateTime? FechaDeSalida { get; set; }
    
        public virtual SubDepartamentos SubDepartamentos { get; set; }
        public virtual Materias_Primas Materias_Primas { get; set; }
    }
}
