//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTM.Models
{
    using RTM.Models.TableDB;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Departamentos
    {

        [Key]
        public int DepartamentoID { get; set; }

        [ForeignKey("TiposDepartamentos")]
        public int? TipoDepartamentoID { get; set; }
        public string Departamento { get; set; }

        public virtual TiposDepartamentos TiposDepartamentos { get; set; }
    }
}
