//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Materias_Primas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materias_Primas()
        {
            this.Area_Produccion_Materias_Primas = new HashSet<Area_Produccion_Materias_Primas>();
            this.Suplidor_Materia_Prima = new HashSet<Suplidor_Materia_Prima>();
        }
    
         [Key]
        public int Materia_PrimaID { get; set; }
        public int? Tipo_MaterialID { get; set; }
        public string Nombre_Materia_Prima { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Area_Produccion_Materias_Primas> Area_Produccion_Materias_Primas { get; set; }
        public virtual Tipo_Material Tipo_Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Suplidor_Materia_Prima> Suplidor_Materia_Prima { get; set; }
    }
}
