//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Ordenes_Clientes_Detalles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ordenes_Clientes_Detalles()
        {
            this.Ordenes_Clientes_Detalles_Colores = new HashSet<Ordenes_Clientes_Detalles_Colores>();
            this.Ordenes_Clientes_Detalles_Dimensiones = new HashSet<Ordenes_Clientes_Detalles_Dimensiones>();
            this.Ordenes_Clientes_Detalles_Modelos = new HashSet<Ordenes_Clientes_Detalles_Modelos>();
            this.Ordenes_Clientes_Detalles_Tipos_Calzados = new HashSet<Ordenes_Clientes_Detalles_Tipos_Calzados>();
        }
    
        [Key]
        public int Orden_Cliente_DetalleID { get; set; }
       
        [ForeignKey("Ordenes_Clientes")]
        public int? Orden_ClienteID { get; set; }

        [ForeignKey("Marca")]
        public int? MarcaID { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual Ordenes_Clientes Ordenes_Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordenes_Clientes_Detalles_Colores> Ordenes_Clientes_Detalles_Colores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordenes_Clientes_Detalles_Dimensiones> Ordenes_Clientes_Detalles_Dimensiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordenes_Clientes_Detalles_Modelos> Ordenes_Clientes_Detalles_Modelos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordenes_Clientes_Detalles_Tipos_Calzados> Ordenes_Clientes_Detalles_Tipos_Calzados { get; set; }
    }
}
