//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Ordenes_Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ordenes_Clientes()
        {
            this.Control_Ubicacion_Piezas = new HashSet<Control_Ubicacion_Piezas>();
            this.Ordenes_Clientes_Detalles = new HashSet<Ordenes_Clientes_Detalles>();
        }
    
        [Key]
        public int Orden_ClienteID { get; set; }

        [ForeignKey("Cliente")]
        public int? ClienteID { get; set; }
        public string CodigoQR { get; set; }
        public int? Cantidad_Calzado_Realizar { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public System.DateTime Fecha_Entrega { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Control_Ubicacion_Piezas> Control_Ubicacion_Piezas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordenes_Clientes_Detalles> Ordenes_Clientes_Detalles { get; set; }
    }
}
