//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Ordenes_Clientes_Detalles
    {
        public Ordenes_Clientes_Detalles()
        {
           
        }
    
        [Key]
        public int Orden_Cliente_DetalleID { get; set; }
       
        [ForeignKey("Ordenes_Clientes")]
        public int? Orden_ClienteID { get; set; }

        [ForeignKey("Marca")]
        public int? MarcaID { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual Ordenes_Clientes Ordenes_Clientes { get; set; }
        public virtual IEnumerable<Ordenes_Clientes_Detalles_Colores> Ordenes_Clientes_Detalles_Colores { get; set; }
        public virtual IEnumerable<Ordenes_Clientes_Detalles_Dimensiones> Ordenes_Clientes_Detalles_Dimensiones { get; set; }
        public virtual IEnumerable<Ordenes_Clientes_Detalles_Modelos> Ordenes_Clientes_Detalles_Modelos { get; set; }
        public virtual IEnumerable<Ordenes_Clientes_Detalles_Tipos_Calzados> Ordenes_Clientes_Detalles_Tipos_Calzados { get; set; }
    }
}
