//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTM.Models
{
    using RTM.Models.TableDB;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RTMDataSourceContainer : DbContext
    {
        public RTMDataSourceContainer()
            : base("name=RTMDataSourceContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Almacen> Almacens { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Area_Produccion_Control_Piezas> Area_Produccion_Control_Piezas { get; set; }
        public virtual DbSet<Area_Produccion_Materias_Primas> Area_Produccion_Materias_Primas { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Colore> Colores { get; set; }
        public virtual DbSet<Control_Ubicacion_Piezas> Control_Ubicacion_Piezas { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Estado> Estados { get; set; }
        public virtual DbSet<Estados_Usuarios_Almacen> Estados_Usuarios_Almacen { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<Materias_Primas> Materias_Primas { get; set; }
        public virtual DbSet<Metricas_Eficiencias> Metricas_Eficiencias { get; set; }
        public virtual DbSet<Modelo> Modelos { get; set; }
        public virtual DbSet<Ordenes_Clientes> Ordenes_Clientes { get; set; }
        public virtual DbSet<Ordenes_Clientes_Detalles> Ordenes_Clientes_Detalles { get; set; }
        public virtual DbSet<Ordenes_Clientes_Detalles_Colores> Ordenes_Clientes_Detalles_Colores { get; set; }
        public virtual DbSet<Ordenes_Clientes_Detalles_Dimensiones> Ordenes_Clientes_Detalles_Dimensiones { get; set; }
        public virtual DbSet<Ordenes_Clientes_Detalles_Modelos> Ordenes_Clientes_Detalles_Modelos { get; set; }
        public virtual DbSet<Ordenes_Clientes_Detalles_Tipos_Calzados> Ordenes_Clientes_Detalles_Tipos_Calzados { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Suplidor_Materia_Prima> Suplidor_Materia_Prima { get; set; }
        public virtual DbSet<Suplidore> Suplidores { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_Calzados> Tipo_Calzados { get; set; }
        public virtual DbSet<Tipo_Material> Tipo_Material { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Usuarios_Almacen> Usuarios_Almacen { get; set; }
        public virtual DbSet<BOM> BOMs { get; set; }
        public virtual DbSet<OperacionesCalzados> OperacionesCalzados { get; set; }
    }
}
