//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Suplidor_Materia_Prima
    {
        [Key]
        public int Suplidor_Materia_PrimaID { get; set; }
        public int? SuplidorID { get; set; }
        public int? AlmacenID { get; set; }
        public int? Materia_PrimaID { get; set; }
        public int? Cantidad { get; set; }
        public System.DateTime? Fecha_Entrega { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Materias_Primas Materias_Primas { get; set; }
        public virtual Suplidore Suplidore { get; set; }
    }
}
