//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuarios_Almacen
    {
        [Key]
        public int Usuario_AlmacenID { get; set; }
        public int? UsuarioID { get; set; }
        public int? AlmacenID { get; set; }
        public int? Estado_Usuario_AlmacenID { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Estados_Usuarios_Almacen Estados_Usuarios_Almacen { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
